server:
   port: 8080

spring:
   datasource:
      platform: postgres
      url: jdbc:postgresql://ec2-34-233-115-14.compute-1.amazonaws.com:5432/daubuujqpniu0a
      username: yuhyoprvegzxtr
      password: d37bf56f6fc59567c50bb8a2839d4bd7830637232285331f77deabb80c953b1a
      driverClassName: org.postgresql.Driver
      initialization-mode: always
      initialize: true
      schema: classpath:/schema-postgresql.sql

   jpa:
      hibernate:
         ddl-auto: create-drop