server:
   port: 8080

spring:
   datasource:
      platform: postgres
      url: jdbc:postgresql://ec2-52-20-166-21.compute-1.amazonaws.com:5432/d52ti571di7dpg
      username: cxgqhpasfqmrpc
      password: 7081cfa100c2a400f43b0a345cb95533b80fa942744ac43a91bf5323a7f7bd79
      driverClassName: org.postgresql.Driver
      initialization-mode: always
      initialize: true
      schema: classpath:/schema-postgresql.sql

   jpa:
      hibernate:
         ddl-auto: create-drop